version: '3.1'
services:

  postgres:
    container_name: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    image: mysql:8.0.2
    environment:
       - MYSQL_ROOT_PASSWORD=my-secret-pw
       - MYSQL_DATABASE=journals
       - MYSQL_ROOT_PASSWORD=admin
    expose:
     - 3306
    ports:
     - "3306:3306"