version: '3.1'
services:

  mysql:
    container_name: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    image: mysql:8.0.2
    environment:
       - MYSQL_ROOT_PASSWORD=admin
       - MYSQL_DATABASE=journals
    expose:
     - 3306
    ports:
     - "3306:3306"

#  news-application:
#    container_name: news-application
#    environment:
#       - MYSQL_ROOT_PASSWORD=admin
#       - MYSQL_DATABASE=journals
#       - MYSQL_ENV_MYSQL_ROOT_PASSWORD=admin
#       - MYSQL_PORT_3306_TCP_PORT=3306
#    build:
#      context: .
#      dockerfile: docker/news-application/Dockerfile
#      args:
#        source: .
#        destination: /
#        startScript: docker/news-application/start-app.sh
#    ports:
#     - "8080:8080"
#    depends_on:
#     - mysql